version: '3'
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
  gogs:
    image: gogs/gogs
    volumes:
      - gogs:/data
    ports:
      - "10022:22"
      - "10080:3000"
  gateway:
    build:
      context: gateway
    ports:
      - "8081:8080"
  config:
    build:
      context: config
    ports:
      - "8082:8080"
  service-user-1:
    build:
      context: service-user
      args:
        instanceId: service-user-1
  service-user-2:
    build:
      context: service-user
      args:
        instanceId: service-user-2
  service-product:
    build: service-product
  service-order:
    build: service-order
    ports:
      - "8080:8080"
volumes:
  gogs: {}